codecov:
  require_ci_to_pass: yes
  precision: 2
  round: down
  layout: "reach,diff,flags,tree"
  behavior: default

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70
        threshold: 0.5
        base: auto
        flags:
          - backend
    patch:
      default:
        target: 80
        threshold: 0.5
    changes:
      default:
        target: 80
        threshold: 0.5

ignore:
  - "node_modules"
  - "**/*.config.js"
  - "**/test/**"
  - "**/*.test.js"

flags:
  backend:
    carryforward: true
    paths:
      - aplicacion\ web-\ inventario/backend
    precision: 2

comment:
  layout: "reach, diff, flags, tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
