# codecov.yml - control básico de thresholds
codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 80%        # meta de cobertura global del proyecto
        threshold: 2%      # tolerancia para cambios pequeños
    patch:
      default:
        target: 75%        # cobertura mínima en líneas modificadas (patch)
        threshold: 0%
  range: "70..100"

ignore:
  - "tests/*"
  - "**/node_modules/**"
  - "**/migrations/**"

parsers:
  gcov:
    branch_detection:
      conditional: yes

# Opciones para fallar el build en Codecov UI (si se configura)
comment:
  layout: "reach, diff, patches"

